### ISSUE TITLE
Unable to build local container

### ISSUE THREAD

**Issue by helrond** [tox-dev/tox-docker#161]
I'm attempting to use `tox-docker` to build a container based on a Dockerfile. According to the docs, this should be possible. Here's my `tox.ini`:
```
tox]
allowlist_externals = docker
envlist = py310
skipsdist = True

[testenv]
skip_install = True
deps =
  -rrequirements.txt
  -rtest_requirements.txt

[testenv:py310]
docker = app
commands =
	coverage run -m pytest -s
	coverage report -m

[docker:app]
dockerfile = {toxinidir}/Dockerfile
```
But when I run this I'm getting the following stack trace:
```
Traceback (most recent call last):
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/session/cmd/run/single.py", line 46, in _evaluate
    code, outcomes = run_commands(tox_env, no_test)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/session/cmd/run/single.py", line 77, in run_commands
    MANAGER.tox_before_run_commands(tox_env)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/plugin/manager.py", line 75, in tox_before_run_commands
    self.manager.hook.tox_before_run_commands(tox_env=tox_env)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox_docker/tox4/plugin.py", line 60, in tox_before_run_commands
    container_configs = [
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox_docker/tox4/plugin.py", line 61, in <listcomp>
    parse_container_config(docker_conf) for docker_conf in docker_confs
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox_docker/tox4/config.py", line 94, in parse_container_config
    image=docker_config["image"],
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/config/sets.py", line 114, in __getitem__
    return self.load(item)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/config/sets.py", line 125, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox/config/of_type.py", line 112, in __call__
    value = self.post_process(value)
  File "/Users/harnold/.pyenv/versions/3.10.8/lib/python3.10/site-packages/tox_docker/tox4/config.py", line 17, in image_required
    raise MissingRequiredSetting("image")
tox_docker.tox4.config.MissingRequiredSetting: image
```

tox 4.4.6
tox-docker 4.1.0
Python 3.10
Mac OS Monterey 12.6

**Comment by dcrosta** [comment]
Hm, this must not be version 4.1.0 somehow. The line the error is coming from in the trace above doesn't even exist in 4.1.0: https://github.com/tox-dev/tox-docker/blob/v4.1.0/tox_docker/tox4/config.py#L17

Can you try uninstalling & reinstalling tox-docker? This ought to work

**Comment by helrond** [comment]
Thanks uninstalling and reinstalling version 4.1.0 worked. I had version 4.0.0 installed previously.
