### ISSUE TITLE
Cannot run container in latest 1.30.0 release

### ISSUE THREAD

**Issue by hectorvs** [tox-dev/tox-docker#21]
Tests started failing with latest tox-docker release:

my tox.ini
```
[tox]
envlist = py36

[testenv]
docker =
    amazon/dynamodb-local

commands =
    pytest --ignore=deploy
```

using the latest version of tox.

Traceback:

```
Traceback (most recent call last):
  File "/Users/hectorv/.virtualenvs/al-ps-ci/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/__init__.py", line 42, in cmdline
    main(args)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/__init__.py", line 66, in main
    exit_code = session.runcommand()
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/__init__.py", line 190, in runcommand
    return self.subcommand_test()
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/__init__.py", line 218, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/commands/run/sequential.py", line 22, in run_sequential
    runtestenv(venv, config)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox/session/commands/run/sequential.py", line 73, in runtestenv
    config.pluginmanager.hook.tox_runtest_pre(venv=venv)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hectorv/.virtualenvs/al-ps-ci/lib/python3.6/site-packages/tox_docker.py", line 137, in tox_runtest_pre
    "Never got answer on port {} from {}".format(containerport, name)
Exception: Never got answer on port 8000/tcp from amazon/dynamodb-local
```

pinning tox-docker to version 1.2.1 fixes the issue.

My docker installation is working correctly since I can `docker run` the container with no problem.

**Comment by dcrosta** [comment]
From the paths in the traceback, it looks like you're running on MacOS? Do you have access to a linux machine to test with? I suspect it will work there.

**Comment by hectorvs** [comment]
just tried it, works perfectly 👌

Thanks for the quick fix!
Seems like it was a weird edge case.
