### ISSUE TITLE
fail tox run if health check fails

### ISSUE THREAD

**Issue by dcrosta** [tox-dev/tox-docker#51]
Currently, a failing health check skips running tests, but reports the tox run as passed ("commands succeeded" in green text in the terminal):

```
$ git diff
diff --git a/tox.ini b/tox.ini
index 8d33c01..e2b9354 100644
--- a/tox.ini
+++ b/tox.ini
@@ -41,7 +41,7 @@ deps = pytest
 commands = py.test [] test_healthcheck.py

 [docker:redis:5-alpine]
-healthcheck_cmd = redis-cli ping | grep -q PONG
+healthcheck_cmd = false
 healthcheck_interval = 1
 healthcheck_timeout = 1
 healthcheck_retries = 30

$ tox -e healthcheck-custom
GLOB sdist-make: /Users/dcrosta/src/tox-docker/setup.py
healthcheck-custom inst-nodeps: /Users/dcrosta/src/tox-docker/.tox/.tmp/package/1/tox-docker-1.5.0.zip
healthcheck-custom installed: appdirs==1.4.3,attrs==19.3.0,certifi==2020.4.5.1,chardet==3.0.4,distlib==0.3.0,docker==4.2.0,filelock==3.0.12,idna==2.9,more-itertools==8.2.0,packaging==20.3,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.7,pytest==5.4.1,requests==2.23.0,six==1.14.0,toml==0.10.0,tox==3.14.6,tox-docker==1.5.0,urllib3==1.25.9,virtualenv==20.0.18,wcwidth==0.1.9,websocket-client==0.57.0
healthcheck-custom docker: run 'redis:5-alpine'
healthcheck-custom docker: health check: 'redis:5-alpine'
____________________________________________________________________________________ summary _____________________________________________________________________________________
  healthcheck-custom: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "/Users/dcrosta/.pyenv/versions/tox-docker-3.8/bin/tox", line 8, in <module>
    sys.exit(cmdline())
[...]
  File "/Users/dcrosta/src/tox-docker/tox_docker.py", line 218, in tox_runtest_pre
    raise HealthCheckFailed("{!r} failed health check".format(image))
tox_docker.HealthCheckFailed: 'redis:5-alpine' failed health check
```

The existing code raises an exception, but Tox 3 seems to print-but-swallow that exception. Tox2 fails when the exception is raised, as was (originally) expected)

**Comment by thenewguy** [comment]
I noticed this while fixing #57 - do you have an idea of what is required to solve?  Happy to put it together but it isn't immediately obvious to me how to fix

**Comment by dcrosta** [comment]
Yeah, I ran out of time this morning to figure out the details here, but it's close...
